!=======================================================================
! Generated by  : PSCAD v4.2.1
!
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Main
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE DSDyn()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

!     SUBR    3PHVSRC       ! 3-Phase Source model

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Parameters

! Electrical Node Indexes

! Control Signals
      REAL    RT_1(31), RT_2(31), RT_3, RT_4(31)
      REAL    RT_5(31), RT_6, DPF, Ia_pha1, RT_7
      REAL    RT_8, Ea_pha1, Ea, Ia, Ea_rms
      REAL    Ia_rms, S, Q, P, RT_9, RT_10, RT_11
      REAL    RT_12, D, Ea_mag1, Ia_mag1, RT_13
      REAL    RT_14(31), RT_15, RT_16, RT_17, Ic
      REAL    Ec, Ib, Eb, Is

! Internal Variables
      REAL    E_MAG, F_RAD, R_PH

! Indexing variables
      INTEGER ISTOF, IT_0                         ! Storage Indexes
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Record local indexes
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage
      NTXFR = NTXFR + 1
      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF

! Record Offset and Increment Storage Counters
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 185
      NPGB      = NPGB + 42
      INODE     = NNODE + 2
      NNODE     = NNODE + 16

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO 100  IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
  100 CONTINUE

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 40

!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      RT_3     = STOF(ISTOF + 63)
      RT_6     = STOF(ISTOF + 126)
      DPF      = STOF(ISTOF + 127)
      Ia_pha1  = STOF(ISTOF + 128)
      RT_7     = STOF(ISTOF + 129)
      RT_8     = STOF(ISTOF + 130)
      Ea_pha1  = STOF(ISTOF + 131)
      Ea       = STOF(ISTOF + 132)
      Ia       = STOF(ISTOF + 133)
      Ea_rms   = STOF(ISTOF + 134)
      Ia_rms   = STOF(ISTOF + 135)
      S        = STOF(ISTOF + 136)
      Q        = STOF(ISTOF + 137)
      P        = STOF(ISTOF + 138)
      RT_9     = STOF(ISTOF + 139)
      RT_10    = STOF(ISTOF + 140)
      RT_11    = STOF(ISTOF + 141)
      RT_12    = STOF(ISTOF + 142)
      D        = STOF(ISTOF + 143)
      Ea_mag1  = STOF(ISTOF + 144)
      Ia_mag1  = STOF(ISTOF + 145)
      RT_13    = STOF(ISTOF + 146)
      RT_15    = STOF(ISTOF + 178)
      RT_16    = STOF(ISTOF + 179)
      RT_17    = STOF(ISTOF + 180)
      Ic       = STOF(ISTOF + 181)
      Ec       = STOF(ISTOF + 182)
      Ib       = STOF(ISTOF + 183)
      Eb       = STOF(ISTOF + 184)
      Is       = STOF(ISTOF + 185)

! Array(1:31) quantities...
      DO 101  IT_0 = 1,31
         RT_1(IT_0) = STOF(ISTOF + 0 + IT_0)
         RT_2(IT_0) = STOF(ISTOF + 31 + IT_0)
         RT_4(IT_0) = STOF(ISTOF + 63 + IT_0)
         RT_5(IT_0) = STOF(ISTOF + 94 + IT_0)
         RT_14(IT_0) = STOF(ISTOF + 146 + IT_0)
  101 CONTINUE

!---------------------------------------
! Transfer from Imports
!---------------------------------------


!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Read Model data (if any)
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF

!---------------------------------------
! Generated code from module definition
!---------------------------------------


! -1:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: Diode
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+9), 0.01, 1000000.0, 1, 0.0&
     &, 0, 0, 100000.0, 100000.0, 0.0, 0.0)

! -1:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: Diode
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+11), 0.01, 1000000.0, 1, 0.&
     &0, 0, 0, 100000.0, 100000.0, 0.0, 0.0)

! -1:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: Diode
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+13), 0.01, 1000000.0, 1, 0.&
     &0, 0, 0, 100000.0, 100000.0, 0.0, 0.0)

! -1:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: Diode
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+15), 0.01, 1000000.0, 1, 0.&
     &0, 0, 0, 100000.0, 100000.0, 0.0, 0.0)

! -1:[source_3] Three Phase Voltage Source Model 2 'Source 1'
! Three Phase Source: Source 1  Type: L
!  Mag: 0.311085197333 kV, Freq: 50.0 Hz, Phase: 0.0 degs, StartUp: 0.05 sec
      E_MAG = 0.311085197333
      F_RAD = 314.159265359
      R_PH  = 0.0*PI_BY180
      CALL EMTDC_3PHVSRC(SS(1), (IBRCH(1)+1), (IBRCH(1)+2), (IBRCH(1)+3)&
     &, 0.05, .TRUE., E_MAG , F_RAD, R_PH)
!

! -1:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: Diode
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+20), 0.01, 1000000.0, 1, 0.&
     &0, 0, 0, 100000.0, 100000.0, 0.0, 0.0)

! -1:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: Diode
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+22), 0.01, 1000000.0, 1, 0.&
     &0, 0, 0, 100000.0, 100000.0, 0.0, 0.0)

! -1:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: Diode
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+24), 0.01, 1000000.0, 1, 0.&
     &0, 0, 0, 100000.0, 100000.0, 0.0, 0.0)

! -1:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: Diode
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+26), 0.01, 1000000.0, 1, 0.&
     &0, 0, 0, 100000.0, 100000.0, 0.0, 0.0)

! -1:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: Diode
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+31), 0.01, 1000000.0, 1, 0.&
     &0, 0, 0, 100000.0, 100000.0, 0.0, 0.0)

! -1:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: Diode
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+29), 0.01, 1000000.0, 1, 0.&
     &0, 0, 0, 100000.0, 100000.0, 0.0, 0.0)

! -1:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: Diode
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+19), 0.01, 1000000.0, 1, 0.&
     &0, 0, 0, 100000.0, 100000.0, 0.0, 0.0)

! -1:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: Diode
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+17), 0.01, 1000000.0, 1, 0.&
     &0, 0, 0, 100000.0, 100000.0, 0.0, 0.0)

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 63) = RT_3
      STOF(ISTOF + 126) = RT_6
      STOF(ISTOF + 127) = DPF
      STOF(ISTOF + 128) = Ia_pha1
      STOF(ISTOF + 129) = RT_7
      STOF(ISTOF + 130) = RT_8
      STOF(ISTOF + 131) = Ea_pha1
      STOF(ISTOF + 132) = Ea
      STOF(ISTOF + 133) = Ia
      STOF(ISTOF + 134) = Ea_rms
      STOF(ISTOF + 135) = Ia_rms
      STOF(ISTOF + 136) = S
      STOF(ISTOF + 137) = Q
      STOF(ISTOF + 138) = P
      STOF(ISTOF + 139) = RT_9
      STOF(ISTOF + 140) = RT_10
      STOF(ISTOF + 141) = RT_11
      STOF(ISTOF + 142) = RT_12
      STOF(ISTOF + 143) = D
      STOF(ISTOF + 144) = Ea_mag1
      STOF(ISTOF + 145) = Ia_mag1
      STOF(ISTOF + 146) = RT_13
      STOF(ISTOF + 178) = RT_15
      STOF(ISTOF + 179) = RT_16
      STOF(ISTOF + 180) = RT_17
      STOF(ISTOF + 181) = Ic
      STOF(ISTOF + 182) = Ec
      STOF(ISTOF + 183) = Ib
      STOF(ISTOF + 184) = Eb
      STOF(ISTOF + 185) = Is

! Array(1:31) quantities...
      DO 102  IT_0 = 1,31
         STOF(ISTOF + 0 + IT_0) = RT_1(IT_0)
         STOF(ISTOF + 31 + IT_0) = RT_2(IT_0)
         STOF(ISTOF + 63 + IT_0) = RT_4(IT_0)
         STOF(ISTOF + 94 + IT_0) = RT_5(IT_0)
         STOF(ISTOF + 146 + IT_0) = RT_14(IT_0)
  102 CONTINUE

!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE DSOut()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

      REAL    EMTDC_VVDC    ! 
!     SUBR    FTN180        ! FFT Calculation
!     SUBR    DGTL_RMS      ! 'RMS Measurement using Digital Samlping'
      REAL    THDN          ! Harmonic Distortion Calculation
      REAL    VBRANCH       ! Voltage across the branch

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Electrical Node Indexes
      INTEGER NT_1, NT_2, NT_3

! Control Signals
      REAL    RT_1(31), RT_2(31), RT_3, RT_4(31)
      REAL    RT_5(31), RT_6, DPF, Ia_pha1, RT_7
      REAL    RT_8, Ea_pha1, Ea, Ia, Ea_rms
      REAL    Ia_rms, S, Q, P, RT_9, RT_10, RT_11
      REAL    RT_12, D, Ea_mag1, Ia_mag1, RT_13
      REAL    RT_14(31), RT_15, RT_16, RT_17, Ic
      REAL    Ec, Ib, Eb, Is

! Internal Variables
      INTEGER IPD_TE, IVD1_1

! Indexing variables
      INTEGER ISTOL, ISTOI, ISTOF, IT_0           ! Storage Indexes
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Record local indexes
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage
      NTXFR = NTXFR + 1
      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)

! Record Offset and Increment Storage Counters
      IPGB      = NPGB
      NPGB      = NPGB + 42
      INODE     = NNODE + 2
      NNODE     = NNODE + 16

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO 100  IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
  100 CONTINUE

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 40

!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      RT_3     = STOF(ISTOF + 63)
      RT_6     = STOF(ISTOF + 126)
      DPF      = STOF(ISTOF + 127)
      Ia_pha1  = STOF(ISTOF + 128)
      RT_7     = STOF(ISTOF + 129)
      RT_8     = STOF(ISTOF + 130)
      Ea_pha1  = STOF(ISTOF + 131)
      Ea       = STOF(ISTOF + 132)
      Ia       = STOF(ISTOF + 133)
      Ea_rms   = STOF(ISTOF + 134)
      Ia_rms   = STOF(ISTOF + 135)
      S        = STOF(ISTOF + 136)
      Q        = STOF(ISTOF + 137)
      P        = STOF(ISTOF + 138)
      RT_9     = STOF(ISTOF + 139)
      RT_10    = STOF(ISTOF + 140)
      RT_11    = STOF(ISTOF + 141)
      RT_12    = STOF(ISTOF + 142)
      D        = STOF(ISTOF + 143)
      Ea_mag1  = STOF(ISTOF + 144)
      Ia_mag1  = STOF(ISTOF + 145)
      RT_13    = STOF(ISTOF + 146)
      RT_15    = STOF(ISTOF + 178)
      RT_16    = STOF(ISTOF + 179)
      RT_17    = STOF(ISTOF + 180)
      Ic       = STOF(ISTOF + 181)
      Ec       = STOF(ISTOF + 182)
      Ib       = STOF(ISTOF + 183)
      Eb       = STOF(ISTOF + 184)
      Is       = STOF(ISTOF + 185)

! Array(1:31) quantities...
      DO 101  IT_0 = 1,31
         RT_1(IT_0) = STOF(ISTOF + 0 + IT_0)
         RT_2(IT_0) = STOF(ISTOF + 31 + IT_0)
         RT_4(IT_0) = STOF(ISTOF + 63 + IT_0)
         RT_5(IT_0) = STOF(ISTOF + 94 + IT_0)
         RT_14(IT_0) = STOF(ISTOF + 146 + IT_0)
  101 CONTINUE

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------

      NT_1  = NODE(INODE + 1)
      NT_2  = NODE(INODE + 2)
      NT_3  = NODE(INODE + 3)

!---------------------------------------
! Read Model data (if any)
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF

!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 10:[voltmetergnd] Voltmeter (Line - Ground) 'Ea'
      Ea = EMTDC_VVDC(SS(1), NT_1, 0)

! 20:[ammeter] Current Meter 'Ia'
      Ia = ( CBR((IBRCH(1)+4), SS(1)))

! 30:[voltmetergnd] Voltmeter (Line - Ground) 'Eb'
      Eb = EMTDC_VVDC(SS(1), NT_3, 0)

! 40:[ammeter] Current Meter 'Ib'
      Ib = ( CBR((IBRCH(1)+6), SS(1)))

! 50:[voltmetergnd] Voltmeter (Line - Ground) 'Ec'
      Ec = EMTDC_VVDC(SS(1), NT_2, 0)

! 60:[ammeter] Current Meter 'Ic'
      Ic = ( CBR((IBRCH(1)+5), SS(1)))

! 70:[ammeter] Current Meter 'Is'
      Is = ( CBR((IBRCH(1)+7), SS(1)))

! 80:[fft] On-Line Frequency Scanner 
!
!  FAST FOURIER TRANSFORMATION
!
      IPD_TE=0
      CALL FTN180(0,0,31,1,50.0,50.0,Ea,IPD_TE,RT_2,RT_1,RT_13)
!

! 90:[rms-inst] Single Phase RMS Meter 
!
      CALL DGTL_RMS(64,50.0,Ea,1.0,0.0,Ea_rms)

! 100:[fft] On-Line Frequency Scanner 
!
!  FAST FOURIER TRANSFORMATION
!
      IPD_TE=0
      CALL FTN180(0,0,31,1,50.0,50.0,Ia,IPD_TE,RT_5,RT_4,RT_15)
!

! 110:[rms-inst] Single Phase RMS Meter 
!
      CALL DGTL_RMS(64,50.0,Ia,1.0,0.0,Ia_rms)

! 120:[datatap] Scalar/Array Tap 
       Ea_mag1 = RT_2(1)

! 130:[datatap] Scalar/Array Tap 
       Ea_pha1 = RT_1(1)

! 140:[datatap] Scalar/Array Tap 
       Ia_mag1 = RT_5(1)

! 150:[mult] Multiplier 
!
      S = Ea_rms * Ia_rms
!

! 160:[datatap] Scalar/Array Tap 
       Ia_pha1 = RT_4(1)

! 170:[sumjct] Summing/Differencing Junctions 
      RT_7 = + Ea_pha1 - Ia_pha1
!

! 180:[trig] Trigonometric Functions 
!  Trig-Func
      RT_8 = SIN(RT_7)
!

! 190:[mult] Multiplier 
!
      RT_17 = RT_8 * Ea_mag1
!

! 200:[mult] Multiplier 
!
      Q = RT_17 * Ia_mag1
!

! 210:[sumjct] Summing/Differencing Junctions 
      RT_6 = + Ea_pha1 - Ia_pha1
!

! 220:[trig] Trigonometric Functions 
!  Trig-Func
      DPF = COS(RT_6)
!

! 230:[mult] Multiplier 
!
      RT_16 = DPF * Ea_mag1
!

! 240:[mult] Multiplier 
!
      P = RT_16 * Ia_mag1
!

! 250:[square] Square 
!
      RT_9 = S * S
!

! 260:[square] Square 
!
      RT_10 = P * P
!

! 270:[square] Square 
!
      RT_11 = Q * Q
!

! 280:[sumjct] Summing/Differencing Junctions 
      RT_12 = + RT_9 - RT_10 - RT_11
!

! 290:[sqrt] Square Root 
!
      IF (RT_12 .LE. 0.0) THEN
         D = 0.0
      ELSE
         D = SQRT(RT_12)
      ENDIF
!

! 300:[thd] Harmonic Distortion Calculator 
! Harmonic Distortion
      RT_3=THDN(31,0,RT_5,RT_14)
!

! 310:[pgb] Output Channel 'Distortion power'

      PGB(IPGB+1) = 1000000.0 * D

! 320:[pgb] Output Channel 'Active power'

      PGB(IPGB+2) = 1000000.0 * P

! 330:[pgb] Output Channel 'Rective power'

      PGB(IPGB+3) = 1000000.0 * Q

! 340:[pgb] Output Channel 'Ia'

      PGB(IPGB+4) = 1000.0 * Ia

! 350:[pgb] Output Channel 'Ia_rms'

      PGB(IPGB+5) = 1000.0 * Ia_rms

! 360:[pgb] Output Channel 'FFT spectrum'

      DO IVD1_1 = 1, 31
         PGB(IPGB+6+IVD1_1-1) = RT_14(IVD1_1)
      ENDDO

! 370:[pgb] Output Channel 'Ea_rms'

      PGB(IPGB+37) = 1000.0 * Ea_rms

! 380:[pgb] Output Channel 'Apparent power'

      PGB(IPGB+38) = 1000000.0 * S

! 390:[pgb] Output Channel '<Untitled>'

      PGB(IPGB+39) = Ia_mag1

! 400:[pgb] Output Channel 'Ea'

      PGB(IPGB+40) = 1000.0 * Ea

! 410:[pgb] Output Channel 'Ia'

      PGB(IPGB+41) = 1000.0 * Ia

! 420:[pgb] Output Channel 'Ea'

      PGB(IPGB+42) = 1000.0 * Ea

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 63) = RT_3
      STOF(ISTOF + 126) = RT_6
      STOF(ISTOF + 127) = DPF
      STOF(ISTOF + 128) = Ia_pha1
      STOF(ISTOF + 129) = RT_7
      STOF(ISTOF + 130) = RT_8
      STOF(ISTOF + 131) = Ea_pha1
      STOF(ISTOF + 132) = Ea
      STOF(ISTOF + 133) = Ia
      STOF(ISTOF + 134) = Ea_rms
      STOF(ISTOF + 135) = Ia_rms
      STOF(ISTOF + 136) = S
      STOF(ISTOF + 137) = Q
      STOF(ISTOF + 138) = P
      STOF(ISTOF + 139) = RT_9
      STOF(ISTOF + 140) = RT_10
      STOF(ISTOF + 141) = RT_11
      STOF(ISTOF + 142) = RT_12
      STOF(ISTOF + 143) = D
      STOF(ISTOF + 144) = Ea_mag1
      STOF(ISTOF + 145) = Ia_mag1
      STOF(ISTOF + 146) = RT_13
      STOF(ISTOF + 178) = RT_15
      STOF(ISTOF + 179) = RT_16
      STOF(ISTOF + 180) = RT_17
      STOF(ISTOF + 181) = Ic
      STOF(ISTOF + 182) = Ec
      STOF(ISTOF + 183) = Ib
      STOF(ISTOF + 184) = Eb
      STOF(ISTOF + 185) = Is

! Array(1:31) quantities...
      DO 102  IT_0 = 1,31
         STOF(ISTOF + 0 + IT_0) = RT_1(IT_0)
         STOF(ISTOF + 31 + IT_0) = RT_2(IT_0)
         STOF(ISTOF + 63 + IT_0) = RT_4(IT_0)
         STOF(ISTOF + 94 + IT_0) = RT_5(IT_0)
         STOF(ISTOF + 146 + IT_0) = RT_14(IT_0)
  102 CONTINUE

!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

